version: '3.8'

services:
  app:
    container_name: "app"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: cmd/Dockerfile
    volumes:
      - ./cmd/config.yaml:/cmd/config.yaml:ro
    command: >
      --config ./cmd/config.yaml
  app-postgres:
    container_name: "app-postgres"
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "spy"
